libcgroup/libcgroup

bootstrap.sh, tests/gunit/004-cgroup_compare_ignore_rule.cpp, tests/gunit/Makefile.am
Googletest is finicky to get properly bundled within the zip.  This commit fixes that.
When testing the zip on Fedora 30, I noticed a small bug in a test and fixed it as well.
=> Fix small issues with distribution zip files

src/Makefile.am
All source soce files which first needs to be generated needs to be listed in
BUILT_SOURCES.
This patch adds to that automake variable parse.c and parse.h because they are
listed below in libcgroup_la_SOURCES.
=> Paralell build fix #7

.gitmodules, .travis.yml, bootstrap.sh, src/api.c, src/libcgroup-internal.h
This patchset was sent to the libcg-devel mailing list in July:
https://sourceforge.net/p/libcg/mailman/message/37074048/
This patchset adds cgroup v2 support to cgcreate.
Since the automated tests have been split into a separate git repo,
those patches will come out in a separate patchset.
Note that the functional test suite still does not support cgroup
v2.  I have been able to test the vast majority of the new code via
unit tests, and the code coverage is excellent... But I don't like
the technical debt that is accumulating by not having cgroup v2
functional tests in place.
For the time being, I tested the changes by hand under a variety of
scenarios:
* Create a single cgroup v1 cgroup
* Create a single cgroup v2 cgroup
* Create a hierarchy of v1 cgroups
* Create a hierarchy of v2 …
=> Add cgroup v2 support to cgcreate

src/api.c
Replace the hardcoded building of the tasks path in
cg_delete_cgroup_controller() and cgroup_delete_cgroup_ext()
with a call to cgroup_build_tasks_procs_path().  By calling
cgroup_build_tasks_procs_path(), both delete functions now
support cgroup v1 and v2.
cgdelete now supports cgroup v2.
=> api.c: Replace hardcoded "/tasks" in delete functions

.github/workflows/continuous-integration.yml
Display the high-level log, test-suite.log, in
the github work for all jobs.  Also, archive the
functional test logs to facilitate debugging a
failed run.
=> github: Improve logging and reporting

src/api.c
Ignore the positive length returned by asprintf() and only act
upon the error code returned from cg_set_control_value().  Previously
cgroup_set_values_recursive() mishandled the error handling when
the value's dirty flag was set.
Reported-by: Github User bharani-viswas
Fixes: 092e4aeb0416f ("api.c: Refactor duplicate logic in cgroup modify and create")
Fixes Issue #21
=> api.c: Fix erroneous error handling in cgroup_set_values_recursive()

.github/workflows/continuous-integration.yml
See the accompanying libcgroup-tests patchset.  This patch
adds logging of the no-container functional test log files.
Note that the no-container tests are automatically invoked
by `make check`, so no changes are required there.
Code is available here:
https://github.com/drakenclimber/libcgroup/tree/issues/nocontainer
Tests are available here:
https://github.com/drakenclimber/libcgroup-tests/tree/issues/nocontainer
Code coverage remained the same at 31.5%:
https://coveralls.io/builds/36846105
Test results are available here:
https://github.com/drakenclimber/libcgroup/runs/1826371745
=> Run tests outside of a container

src/api.c, src/libcgroup-internal.h, src/libcgroup.map, src/tools/Makefile.am, src/tools/cgget.c, src/wrapper.c
Unlike the rest of libcgroup, the current implementation of cgget
uses arrays of strings to represent cgroups, controllers, and
settings.  The rest of the library utilizes the cgroup struct to
represent the hierarchy.
In preparation for the development of a cgroup v1/v2 abstraction
layer, this patchset refactors cgget to utilize struct cgroup and
better match the rest of the code base.  Note that patch #5 is a
complete re-write; it will likely be easier to review it as if it
were a new file rather than trying to decipher the git diff.
This patchset is largely intended to be nonfunctional and utilizes
the extensive cgget tests patchset sent out earlier [1].  During the
development of this code and the corresponding tests, I noticed in
a few error cases that the previous cgget would return …
=> Refactor cgget

src/daemon/Makefile.am
Code coverage was not being gathered for src/daemon.
Add code coverage support for this directory.
=> Makefile: Run code coverage on the daemon folder

src/api.c, src/libcgroup-internal.h
When cgroup_modify_cgroup() invokes cgroup_set_values_recursive(),
some of the settings within the cgroup may not be writable.  Avoid
failing the entire write by ignoring write failures on settings that
do not explicitly have the dirty flag set.
=> api.c: Don't fail a recursive write if value isn't dirty

src/bindings/Makefile.am, src/daemon/Makefile.am, src/pam/Makefile.am, src/tools/Makefile.am
Remove .libs from Makefile.am files.  Suggested by
github user @orbea.
=> build: Remove .libs from Makefile.am files.

src/libcgroup.map, src/tools/lssubsys.c
Ignore a hierarchy value of zero for cgroup v2 controllers.
This change adds minimal cgroup v2 support to lssubsys.
=> Add cgroup v2 support to lssubsys

src/tools/cgget.c
Fix a segmentation fault when cgget is invoked in the
following form:
cgget CroupName
parse_opt_args() was erroneously expecting a previously
populated struct cgroup in this case, and we were indexing
out of bounds of the cg_list.
Fixes: 1b7d606fa12a ("cgget: Major refactor")
=> cgget: Fix segfault when no flags provided

src/libcgroup.map
Update the version number for the most recent exported
functions.
=> libcgroup.map: Update version number

.github/actions/setup-libcgroup/action.yml
Run apt update before apt install
=> github: Run apt update before apt install

include/libcgroup/config.h, include/libcgroup/error.h, include/libcgroup/groups.h, include/libcgroup/init.h, include/libcgroup/iterators.h, include/libcgroup/log.h, include/libcgroup/tasks.h, src/bindings/libcgroup.p, src/daemon/cgrulesengd.h, src/libcgroup-internal.h, src/tools/tools-common.h
The macros __BEGIN_DECLS and __END_DECLS are a GNU-ism found in
glibc and uClibc, but not musl.  We replace them by the more general
extern "C" { ... } block exposed only if we have __cplusplus.
Forward ported from a patch by Anthony G. Basile <blueness@gentoo.org>.
Signed-off-by: Alex Xu (Hello71) <alex_y_xu@yahoo.ca>
=> Replace __BEGIN_DECLS and __END_DECLS with extern "C".

.github/actions/setup-libcgroup/action.yml
On self-hosted github machines, the working directory for
libcgroup is reused from one run to the next.  This is fine
for the root of the directory as the proper git clean/reset
commands are issues.  But this is problematic for the git
submodules like the tests/ folder because clean/reset is not
run there.
For the github continuous integration, remove the tests/
directory entirely and rely on ./bootstrap.sh to recreate and
populate it.
=> github: Delete the tests folder before bootstrap

.github/actions/setup-libcgroup/action.yml, .github/workflows/continuous-integration.yml
Improve code coverage collection by utilizing the "-i" flag
prior to the run.  This allows coverage on #ifdef'ed code.
Also, archive the code coverage files for later analysis if
desired.
=> github: Improve code coverage collection

.github/workflows/continuous-integration.yml
Fix merge collision in the gathering of the v1/v2
code coverage metrics.
=> github: Fix merge collision in v1/v2 code coverage

README.md
The master branch was renamed to main, but the build status
badge wasn't updated as part of this change.  Display the
build status of the main branch in README.md
=> README.md: Display status of main branch in build status badge

.github/workflows/continuous-integration.yml
The cgroup v2 job is being run on a self-hosted runner that
re-uses the workspace.  Delete the local workspace on all
self-hosted runners prior to cloning the repo.
=> github: Force a fresh clone on all self-hosted runners

src/api.c, src/libcgroup-internal.h
Allow reading/writing from cgroup.* files (such as cgroup.type
and cgroup.procs) on cgroup v2 filesystems.
Closes: https://github.com/libcgroup/libcgroup/issues/73
=> api.c: Allow reading/writing from cgroup.* files in cgroup v2

.github/workflows/continuous-integration.yml, SECURITY.md, src/api.c
* Add a security document that outlines the process for handling security-related vulnerabilities
* Add a continuous integration step that utilizes the CodeQL scanning tool.  It [currently reports](https://github.com/drakenclimber/libcgroup/security/code-scanning?query=is%3Aopen+branch%3Aissues%2Fcodeql)
four issues in Googlemock (which we'll obviously ignore) and one issue in libcgroup itself.  Not
sure yet if this is an issue we should address or not.
=> ENH: Add Security Features

src/api.c
Commit 498530a1d744 ("cgcreate, tools: Allow cgroup creation with
no controllers attached") attempted to add support to allow the
creation of a cgroup v2 cgroup with no controllers attached.  This
patch did create the requested cgroup, but it still required there
to be at least one valid controller _available_ to attach to.
Rework the aforementioned logic so that the cgroup can be created
if there's a valid cgroup v2 mount - even if there are no v2
controllers available.
Fixes: 498530a1d744 ("cgcreate, tools: Allow cgroup creation with no controllers attached")
=> api.c: Allow creation of a v2 cgroup with no controllers

.github/workflows/continuous-integration.yml
It performs differential ShellCheck scans and report results directly in pull request.
documentation: https://github.com/redhat-plumbers-in-action/differential-shellcheck
Signed-off-by: Jan Macku <jamacku@redhat.com>
Reviewed-by: Kamalesh Babulal <kamalesh.babulal@oracle.com>
=> ci(lint): add shell linter - Differential ShellCheck
